# Based on https://gist.github.com/y0ssar1an/df2dab474520c4086926f672c52db139
language: go
go:
  - 1.12.x

os:
  - linux
  - osx
  - windows

dist: xenial

env:
  - GO111MODULE=on # GO111MODULE will be unnecessary when Go 1.13 lands.
#  - GOFLAGS='-mod vendor'

# Only clone the most recent commit.
git:
  depth: 1

install: true

# Email me until we add slack integration
#notifications:
#  email: false

#before_script:
#  - go install github.com/golangci/golangci-lint/cmd/golangci-lint

script:
#  - golangci-lint run       # run a bunch of code checkers/linters in parallel
  - go build .
  - go test -v -race ./...  # Run all the tests with the race detector enabled
